{{ if .Values.otelCollector.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "o11y-collector.fullname" . }}
  labels:
    app: {{ template "o11y-collector.name" . }}
    component: otel-collector
    chart: {{ template "o11y-collector.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | trim | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range $key, $port := .Values.service.ports }}
  - name: {{ $key }}
    port: {{ $port.containerPort }}
    targetPort: {{ $port.targetPort }}
    protocol: {{ $port.protocol }}
  {{- end }}
  selector:
    app: {{ template "o11y-collector.name" . }}
    component: otel-collector
    release: {{ .Release.Name }}
{{- end }}
