---
# Source: splunk-otel-collector/templates/configmap-fluentd-json.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: default-splunk-otel-collector-fluentd-json
  namespace: default
  labels:
    app.kubernetes.io/name: splunk-otel-collector
    helm.sh/chart: splunk-otel-collector-0.105.2
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: default
    app.kubernetes.io/version: "0.105.0"
    app: splunk-otel-collector
    chart: splunk-otel-collector-0.105.2
    release: default
    heritage: Helm
data:
  source.containers.parse.conf: |-
    @type json
    time_format %Y-%m-%dT%H:%M:%S.%NZ

  output.filter.conf: ""

  output.transform.conf: ""
