version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "helm-charts/splunk-otel-collector"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "examples/enable-operator-and-auto-instrumentation/rendered_manifests/operator"
    schedule:
      interval: "daily"
