{{ if .Values.otelCollector.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "splunk-otel-collector.fullname" . }}-otel-collector
  labels:
    {{- include "splunk-otel-collector.commonLabels" . | nindent 4 }}
    app: {{ template "splunk-otel-collector.name" . }}
    chart: {{ template "splunk-otel-collector.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  relay: |
    {{- $config := include "splunk-otel-collector.otelCollectorConfig" . | fromYaml }}
    {{- .Values.otelCollector.config | mustMergeOverwrite $config | toYaml | nindent 4 }}
{{- end }}
