{{- if .Values.obi.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: splunk-otel-collector-obi-env
  namespace: {{ template "splunk-otel-collector.namespace" . }}
  labels:
    {{- include "splunk-otel-collector.commonLabels" . | nindent 4 }}
    app: {{ template "splunk-otel-collector.name" . }}
    chart: {{ template "splunk-otel-collector.chart" . }}
    release: {{ .Release.Name }}
data:
  OTEL_EBPF_KUBE_CLUSTER_NAME: {{ .Values.clusterName | quote }}
{{- end }}
