{{ if .Values.gateway.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "splunk-otel-collector.fullname" . }}-otel-collector
  namespace: {{ template "splunk-otel-collector.namespace" . }}
  labels:
    {{- include "splunk-otel-collector.commonLabels" . | nindent 4 }}
    app: {{ template "splunk-otel-collector.name" . }}
    chart: {{ template "splunk-otel-collector.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  relay: |
    {{- $defaultConfig := include "splunk-otel-collector.gatewayConfig" . | fromYaml }}
    {{- .Values.gateway.config | mustMergeOverwrite $defaultConfig | toYaml | nindent 4 }}
{{- end }}
