{{ if .Values.otelCollector.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "splunk-otel-collector.fullname" . }}-otel-collector
  labels:
    app: {{ template "splunk-otel-collector.name" . }}
    chart: {{ template "splunk-otel-collector.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/name: {{ template "splunk-otel-collector.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Release.Service }}
data:
  relay: |
    {{- $config := include "splunk-otel-collector.otelCollectorConfig" . | fromYaml }}
    {{- .Values.otelCollector.config | mustMergeOverwrite $config | toYaml | nindent 4 }}
{{- end }}
