{{ if .Values.otelAgent.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "splunk-otel-collector.fullname" . }}-otel-agent
  labels:
    app: {{ template "splunk-otel-collector.name" . }}
    chart: {{ template "splunk-otel-collector.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/name: {{ template "splunk-otel-collector.name" . }}
data:
  relay: |
    {{- $config := include "splunk-otel-collector.otelAgentConfig" . | fromYaml }}
    {{- .Values.otelAgent.config | mustMergeOverwrite $config | toYaml | nindent 4 }}
{{- end }}
