{{ $clusterReceiver := fromYaml (include "splunk-otel-collector.clusterReceiver" .) }}
{{ if and $clusterReceiver.enabled (eq (include "splunk-otel-collector.metricsEnabled" .) "true") (eq (include "splunk-otel-collector.distribution" .) "eks/fargate") }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "splunk-otel-collector.clusterReceiverNodeDiscovererScript" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "splunk-otel-collector.commonLabels" . | nindent 4 }}
    app: {{ template "splunk-otel-collector.name" . }}
    chart: {{ template "splunk-otel-collector.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  script: |
  {{- (.Files.Get "scripts/init-eks-fargate-cluster-receiver.sh") | nindent 4 }}
{{- end }}
