---
# Source: splunk-otel-collector/templates/configmap-obi.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: splunk-otel-collector-obi-env
  namespace: default
  labels:
    app.kubernetes.io/name: splunk-otel-collector
    helm.sh/chart: splunk-otel-collector-0.144.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: default
    app.kubernetes.io/version: "0.144.0"
    app: splunk-otel-collector
    chart: splunk-otel-collector-0.144.0
    release: default
data:
  OTEL_EBPF_KUBE_CLUSTER_NAME: "CHANGEME"
