---
# Source: splunk-otel-collector/templates/configmap-obi.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: default-obi-env
  namespace: default
  labels:
    app.kubernetes.io/name: splunk-otel-collector
    helm.sh/chart: splunk-otel-collector-0.141.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: default
    app.kubernetes.io/version: "0.141.0"
    app: splunk-otel-collector
    component: obi-config
    chart: splunk-otel-collector-0.141.0
    release: default
    heritage: Helm
data:
  OTEL_EBPF_KUBE_CLUSTER_NAME: "CHANGEME"
