---
# Source: splunk-otel-collector/charts/certmanager/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: default-certmanager
  namespace: default
  labels:
    app: certmanager
    app.kubernetes.io/name: certmanager
    app.kubernetes.io/instance: default
    app.kubernetes.io/component: "controller"
    app.kubernetes.io/version: "v1.12.2"
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: certmanager-v1.12.2
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 9402
    name: tcp-prometheus-servicemonitor
    targetPort: 9402
  selector:
    app.kubernetes.io/name: certmanager
    app.kubernetes.io/instance: default
    app.kubernetes.io/component: "controller"
