---
# Source: splunk-otel-collector/charts/certmanager/templates/webhook-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: default-certmanager-webhook
  namespace: default
  labels:
    app: webhook
    app.kubernetes.io/name: webhook
    app.kubernetes.io/instance: default
    app.kubernetes.io/component: "webhook"
    app.kubernetes.io/version: "v1.11.0"
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: certmanager-v1.11.0
data:
