clusterName: akhi-splunk-otel-collector
splunkObservability:
  realm: "lab0"
  accessToken: c7fckTLjATKG-Uo4dS1bSQ
  apiUrl: https://app.lab0.signalfx.com
  ingestUrl: https://ingest.lab0.signalfx.com

agent:
  enabled: true
gateway:
  enabled: true
clusterReceiver:
  enabled: true
