# One of 'breaking', 'deprecation', 'new_component', 'enhancement', 'bug_fix'
change_type: "enhancement"
# The name of the component, or a single word describing the area of concern, (e.g. agent, clusterReceiver, gateway, operator, chart, other)
component: "chart"
# A brief description of the change. Surround your text with quotes ("") if it needs to start with a backtick (`).
note: "Enable support for custom propagators in `spec.propagators` within Instrumentation Configuration."
# One or more tracking issues related to the change
issues: ["https://github.com/signalfx/splunk-otel-collector-chart/issues/1663"]
# (Optional) One or more lines of additional information to render under the primary note.
# These lines will be padded with 2 spaces and then inserted directly into the document.
# Use pipe (|) for multiline entries.
subtext:
  This change allows users to specify custom propagators in `spec.propagators` when configuring OpenTelemetry Instrumentation.
