# One of 'breaking', 'deprecation', 'new_component', 'enhancement', 'bug_fix'
change_type: bug_fix
# The name of the component, or a single word describing the area of concern, (e.g. agent, clusterReceiver, gateway, operator, chart, other)
component: agent
# A brief description of the change. Surround your text with quotes ("") if it needs to start with a backtick (`).
note: Fix Prometheus autodetect metric filtering
# One or more tracking issues related to the change
issues: []
# (Optional) One or more lines of additional information to render under the primary note.
# These lines will be padded with 2 spaces and then inserted directly into the document.
# Use pipe (|) for multiline entries.
subtext: |
  A [change was introduced](https://github.com/signalfx/splunk-otel-collector-chart/pull/2141) in `v0.138.0` that
  incorrectly set filters to only keep Istio and Envoy related metrics when `autodetect.prometheus` is enabled.
  The filtering should keep all Prometheus metrics and only filter when `autodetect.prometheus` is disabled, and
  `autodetect.istio` is enabled.
