# One of 'breaking', 'deprecation', 'new_component', 'enhancement', 'bug_fix'
change_type: enhancement
# The name of the component, or a single word describing the area of concern, (e.g. agent, clusterReceiver, gateway, operator, chart, other)
component: chart
# A brief description of the change. Surround your text with quotes ("") if it needs to start with a backtick (`).
note: Adds configuration option for Splunk Platform metrics sourcetype
# One or more tracking issues related to the change
issues: [1941]
# (Optional) One or more lines of additional information to render under the primary note.
# These lines will be padded with 2 spaces and then inserted directly into the document.
# Use pipe (|) for multiline entries.
subtext: |
  - Users can override the metrics sourcetype for Splunk Platform using the `splunk.com/sourcetypeMetrics` annotation or the `.Values.splunkPlatform.sourcetypeMetrics` Helm value.
  - See `advanced-configuration.md` for detailed precedence and usage notes.
