name: Ensure valid and up-to-date Changelog

on: pull_request

jobs:
  validate-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Helm
        uses: azure/setup-helm@v3.5

      - name: Setup ct (chart testing)
        uses: helm/chart-testing-action@v2.4.0

      - name: Run Helm chart-testing (lint)
        run: make lint

      - name: Validate changelog files
        run: make chlog-validate

      - name: Read current version of the Chart
        id: read-chart
        uses: cumulusds/get-yaml-paths-action@v1
        with:
          file: helm-charts/splunk-otel-collector/Chart.yaml
          version: version

      - name: Ensure that CHANGELOG.md has an entry for the current version
        id: read-changelog
        uses: mindsers/changelog-reader-action@v2
        with:
          version: ${{ steps.read-chart.outputs.version }}
          path: ./CHANGELOG.md
